version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - '3310:3306'
    volumes: 
      - /home/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9095:8080